version: '3.9'

services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env/mongodb.env
    volumes:
      - ./mongodb/data:/data/db
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 500M
    secrets:
      - source: mongodb
      - target: /run/secrets/mongo-root
    networks:
      - mongodb_network

  mongodb-express:
    image: mongo-express
    ports:
      - 8081:8081
    env_file:
      - .env/mongodb-express.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M
    networks:
      - mongodb_network

secrets:
  mongodb:
    external: true

networks:
  mongodb_network: 
    name: mongodb_network
    driver: overlay
    driver_opts:
      encrypted: true